// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Synaxis.InferenceGateway.Infrastructure.ControlPlane;

#nullable disable

namespace Synaxis.InferenceGateway.Infrastructure.Migrations
{
    [DbContext(typeof(SynaxisDbContext))]
    [Migration("20260210112019_FixPendingModelChanges2")]
    partial class FixPendingModelChanges2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "identity");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Audit.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("NewValues")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PartitionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreviousValues")
                        .HasColumnType("jsonb");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Action");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PartitionDate");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", "audit", t =>
                        {
                            t.HasCheckConstraint("CK_AuditLog_Action", "\"Action\" IN ('Create', 'Update', 'Delete', 'Read', 'Login', 'Logout', 'ApiCall', 'PermissionChange', 'ConfigChange')");
                        });
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAutoOptimization")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDefaultGroup")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RateLimitRpm")
                        .HasColumnType("integer");

                    b.Property<int?>("RateLimitTpm")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Status");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique();

                    b.ToTable("Groups", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_Group_Status", "\"Status\" IN ('Active', 'Suspended', 'Archived')");
                        });
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("CompanySize")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LegalAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlanTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrimaryContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequireMfa")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SupportEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Organizations", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_Organization_PlanTier", "\"PlanTier\" IN ('Free', 'Starter', 'Professional', 'Enterprise', 'Custom')");

                            t.HasCheckConstraint("CK_Organization_Status", "\"Status\" IN ('Active', 'Suspended', 'PendingActivation', 'Deactivated')");
                        });
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.OrganizationSettings", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAuditLogExport")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowAutoOptimization")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowCustomProviders")
                        .HasColumnType("boolean");

                    b.Property<int>("AuditLogRetentionDays")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultRateLimitRpm")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultRateLimitTpm")
                        .HasColumnType("integer");

                    b.Property<int>("JwtTokenLifetimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxGroups")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRequestBodySizeBytes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<long?>("MonthlyTokenQuota")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId");

                    b.ToTable("OrganizationSettings", "identity");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("Status");

                    b.ToTable("Users", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_User_Status", "\"Status\" IN ('Active', 'Suspended', 'PendingVerification', 'Deactivated')");
                        });
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.UserGroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("IsPrimary");

                    b.HasIndex("UserId", "GroupId")
                        .IsUnique();

                    b.ToTable("UserGroupMemberships", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_UserGroupMembership_GroupRole", "\"GroupRole\" IN ('Admin', 'Member', 'Viewer')");
                        });
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.UserOrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAutoOptimization")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrganizationRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("PrimaryGroupId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RateLimitRpm")
                        .HasColumnType("integer");

                    b.Property<int?>("RateLimitTpm")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PrimaryGroupId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique();

                    b.ToTable("UserOrganizationMemberships", "identity", t =>
                        {
                            t.HasCheckConstraint("CK_UserOrgMembership_OrganizationRole", "\"OrganizationRole\" IN ('Owner', 'Admin', 'Member', 'Guest')");

                            t.HasCheckConstraint("CK_UserOrgMembership_Status", "\"Status\" IN ('Active', 'Suspended', 'Invited', 'Rejected')");
                        });
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId", "OrganizationId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoleAssignments", "identity");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RateLimitRpm")
                        .HasColumnType("integer");

                    b.Property<int?>("RateLimitTpm")
                        .HasColumnType("integer");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Scopes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("ApiKeys", "operations");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.OrganizationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomAlias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("InputCostPer1MTokens")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("OutputCostPer1MTokens")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("OrganizationId", "ModelId")
                        .IsUnique();

                    b.ToTable("OrganizationModels", "operations");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.OrganizationProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyEncrypted")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("CustomEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("HealthCheckEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("InputCostPer1MTokens")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("OutputCostPer1MTokens")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RateLimitRpm")
                        .HasColumnType("integer");

                    b.Property<int?>("RateLimitTpm")
                        .HasColumnType("integer");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsTools")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsVision")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("OrganizationId", "ProviderId")
                        .IsUnique();

                    b.ToTable("OrganizationProviders", "operations");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.ProviderHealthStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageLatencyMs")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CooldownUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HealthScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInCooldown")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationProviderId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SuccessRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("IsHealthy");

                    b.HasIndex("LastCheckedAt");

                    b.HasIndex("OrganizationProviderId")
                        .IsUnique();

                    b.ToTable("ProviderHealthStatuses", "operations");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.RoutingStrategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("FallbackToPaid")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxCostPer1MTokens")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<int?>("MaxLatencyMs")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinHealthScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PrioritizeFreeProviders")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireStreaming")
                        .HasColumnType("boolean");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique();

                    b.ToTable("RoutingStrategies", "operations", t =>
                        {
                            t.HasCheckConstraint("CK_RoutingStrategy_StrategyType", "\"StrategyType\" IN ('CostOptimized', 'Performance', 'Reliability', 'Custom')");
                        });
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Platform.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ContextWindowTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsTools")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsVision")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProviderId", "CanonicalId")
                        .IsUnique();

                    b.ToTable("Models", "platform");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Platform.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DefaultApiKeyEnvironmentVariable")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("DefaultInputCostPer1MTokens")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<decimal?>("DefaultOutputCostPer1MTokens")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFreeTier")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsTools")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsVision")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Providers", "platform", t =>
                        {
                            t.HasCheckConstraint("CK_Provider_ProviderType", "\"ProviderType\" IN ('OpenAI', 'Anthropic', 'Google', 'Cohere', 'Azure', 'AWS', 'Cloudflare', 'Generic')");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Group", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", "Organization")
                        .WithMany("Groups")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.OrganizationSettings", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", "Organization")
                        .WithOne("Settings")
                        .HasForeignKey("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.OrganizationSettings", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Role", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", "Organization")
                        .WithMany("Roles")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.UserGroupMembership", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Group", "Group")
                        .WithMany("UserMemberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.UserOrganizationMembership", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", "Organization")
                        .WithMany("UserMemberships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Group", "PrimaryGroup")
                        .WithMany()
                        .HasForeignKey("PrimaryGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", "User")
                        .WithMany("OrganizationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("PrimaryGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.UserRole", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.ProviderHealthStatus", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.OrganizationProvider", "OrganizationProvider")
                        .WithMany()
                        .HasForeignKey("OrganizationProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationProvider");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Platform.Model", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Platform.Provider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Group", b =>
                {
                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Roles");

                    b.Navigation("Settings");

                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("OrganizationMemberships");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Platform.Provider", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
