// <copyright file="ChatChoice.cs" company="Synaxis">
// Copyright (c) Synaxis. All rights reserved.
// </copyright>

namespace Synaxis.Api.DTOs.OpenAi
{
    using System.Text.Json.Serialization;

    /// <summary>
    /// Represents a chat completion choice.
    /// </summary>
    public sealed class ChatChoice
    {
        /// <summary>
        /// Gets or sets the index of the choice.
        /// </summary>
        [JsonPropertyName("index")]
        public int Index { get; set; }

        /// <summary>
        /// Gets or sets the message generated by the model.
        /// </summary>
        [JsonPropertyName("message")]
        public ChatMessage Message { get; set; } = new ChatMessage();

        /// <summary>
        /// Gets or sets the reason the model stopped generating.
        /// </summary>
        [JsonPropertyName("finish_reason")]
        public string FinishReason { get; set; } = null!;

        /// <summary>
        /// Gets or sets the logprobs information.
        /// </summary>
        [JsonPropertyName("logprobs")]
        public object Logprobs { get; set; } = null!;
    }
}
