// <copyright file="CompletionChoice.cs" company="Synaxis">
// Copyright (c) Synaxis. All rights reserved.
// </copyright>

namespace Synaxis.Api.DTOs.OpenAi
{
    using System.Text.Json.Serialization;

    /// <summary>
    /// Represents a text completion choice.
    /// </summary>
    public sealed class CompletionChoice
    {
        /// <summary>
        /// Gets or sets the index of the choice.
        /// </summary>
        [JsonPropertyName("index")]
        public int Index { get; set; }

        /// <summary>
        /// Gets or sets the text generated by the model.
        /// </summary>
        [JsonPropertyName("text")]
        public string Text { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the reason the model stopped generating.
        /// </summary>
        [JsonPropertyName("finish_reason")]
        public string FinishReason { get; set; } = null!;

        /// <summary>
        /// Gets or sets the logprobs information.
        /// </summary>
        [JsonPropertyName("logprobs")]
        public object Logprobs { get; set; } = null!;
    }
}
