// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Synaxis.InferenceGateway.Infrastructure.ControlPlane;

#nullable disable

namespace Synaxis.InferenceGateway.Infrastructure.ControlPlane.Migrations
{
    [DbContext(typeof(ControlPlaneDbContext))]
    [Migration("20260209141418_RemoveAuditLogSchema")]
    partial class RemoveAuditLogSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectUsers", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectUsers");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.DeviationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Mitigation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Deviations");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.GlobalModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("ContextWindow")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("InputPrice")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<bool>("IsOpenWeights")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxOutputTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("OutputPrice")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<DateTime?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("SupportsAudio")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsReasoning")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsStructuredOutput")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsTools")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsVision")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("GlobalModels");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.ModelAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TargetModel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ModelAliases");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.ModelCombo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OrderedModelsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ModelCombos");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.ModelCost", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("CostPerToken")
                        .HasColumnType("numeric");

                    b.Property<bool>("FreeTier")
                        .HasColumnType("boolean");

                    b.HasKey("Provider", "Model");

                    b.ToTable("ModelCosts");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.OAuthAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("AccessTokenEncrypted")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<byte[]>("RefreshTokenEncrypted")
                        .HasColumnType("bytea");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("OAuthAccounts");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.ProviderAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ProviderAccounts");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.ProviderModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GlobalModelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("OverrideInputPrice")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<decimal?>("OverrideOutputPrice")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderSpecificId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("RateLimitRPM")
                        .HasColumnType("integer");

                    b.Property<int?>("RateLimitTPM")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GlobalModelId");

                    b.ToTable("ProviderModels");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.QuotaSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("QuotaJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.HasKey("Id");

                    b.ToTable("QuotaSnapshots");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.RequestLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("RequestLogs");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.RoutingPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PolicyJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("RoutingPolicies");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ByokKeyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedByokKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.TenantModelLimit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AllowedRPM")
                        .HasColumnType("integer");

                    b.Property<string>("GlobalModelId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("MonthlyBudget")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GlobalModelId");

                    b.ToTable("TenantModelLimits");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.TokenUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostEstimate")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.ToTable("TokenUsages");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProviderUserId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAutoOptimization")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsDefaultGroup")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RateLimitRpm")
                        .HasColumnType("integer");

                    b.Property<int?>("RateLimitTpm")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique();

                    b.ToTable("Groups", "identity");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Invitation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AcceptedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CancelledBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeclinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeclinedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InvitedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("InvitedBy");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Status");

                    b.HasIndex("TeamId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("TeamId", "Email", "Status");

                    b.ToTable("Invitations", "identity");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BillingEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("CompanySize")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Industry")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LegalAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PlanTier")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PrimaryContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequireMfa")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SupportEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("TaxId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("WebsiteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Organizations", "identity");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.OrganizationSettings", b =>
                {
                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAuditLogExport")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowAutoOptimization")
                        .HasColumnType("boolean");

                    b.Property<bool>("AllowCustomProviders")
                        .HasColumnType("boolean");

                    b.Property<int>("AuditLogRetentionDays")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultRateLimitRpm")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultRateLimitTpm")
                        .HasColumnType("integer");

                    b.Property<int>("JwtTokenLifetimeMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxGroups")
                        .HasColumnType("integer");

                    b.Property<int>("MaxRequestBodySizeBytes")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("integer");

                    b.Property<long?>("MonthlyTokenQuota")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("OrganizationId");

                    b.ToTable("OrganizationSettings", "identity");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IsSystemRole");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasFilter("\"OrganizationId\" IS NOT NULL");

                    b.ToTable("Roles", "identity");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_Users1");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Users", "identity");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.UserGroupMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("IsPrimary");

                    b.HasIndex("UserId", "GroupId")
                        .IsUnique();

                    b.ToTable("UserGroupMemberships", "identity");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.UserOrganizationMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowAutoOptimization")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("OrganizationRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("PrimaryGroupId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RateLimitRpm")
                        .HasColumnType("integer");

                    b.Property<int?>("RateLimitTpm")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("PrimaryGroupId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId", "OrganizationId")
                        .IsUnique();

                    b.ToTable("UserOrganizationMemberships", "identity");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "identity");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.ApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RateLimitRpm")
                        .HasColumnType("integer");

                    b.Property<int?>("RateLimitTpm")
                        .HasColumnType("integer");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RevokedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Scopes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id")
                        .HasName("PK_ApiKeys1");

                    b.HasIndex("IsActive");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("ApiKeys", "operations");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.OrganizationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CustomAlias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("InputCostPer1MTokens")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ModelId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("OutputCostPer1MTokens")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("ModelId");

                    b.HasIndex("OrganizationId", "ModelId")
                        .IsUnique();

                    b.ToTable("OrganizationModels", "operations");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.OrganizationProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApiKeyEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("CustomEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("HealthCheckEnabled")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("InputCostPer1MTokens")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("OutputCostPer1MTokens")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RateLimitRpm")
                        .HasColumnType("integer");

                    b.Property<int?>("RateLimitTpm")
                        .HasColumnType("integer");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsTools")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsVision")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("ProviderId");

                    b.HasIndex("OrganizationId", "ProviderId")
                        .IsUnique();

                    b.ToTable("OrganizationProviders", "operations");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.ProviderHealthStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AverageLatencyMs")
                        .HasColumnType("integer");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CooldownUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("HealthScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<bool>("IsHealthy")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInCooldown")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastCheckedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OrganizationProviderId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("SuccessRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("LastCheckedAt");

                    b.HasIndex("OrganizationProviderId")
                        .IsUnique();

                    b.HasIndex("OrganizationId", "IsHealthy");

                    b.ToTable("ProviderHealthStatuses", "operations");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.RoutingStrategy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("FallbackToPaid")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("MaxCostPer1MTokens")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<int?>("MaxLatencyMs")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MinHealthScore")
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PrioritizeFreeProviders")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireStreaming")
                        .HasColumnType("boolean");

                    b.Property<string>("StrategyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "IsDefault")
                        .IsUnique()
                        .HasFilter("\"IsDefault\" = true");

                    b.ToTable("RoutingStrategies", "operations");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Platform.Model", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CanonicalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("ContextWindowTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxOutputTokens")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProviderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsTools")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsVision")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ProviderId", "CanonicalId")
                        .IsUnique();

                    b.ToTable("Models", "platform");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Platform.Provider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseEndpoint")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DefaultApiKeyEnvironmentVariable")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal?>("DefaultInputCostPer1MTokens")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<decimal?>("DefaultOutputCostPer1MTokens")
                        .HasPrecision(18, 9)
                        .HasColumnType("numeric(18,9)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFreeTier")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("SupportsStreaming")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsTools")
                        .HasColumnType("boolean");

                    b.Property<bool>("SupportsVision")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Providers", "platform");
                });

            modelBuilder.Entity("ProjectUsers", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.ApiKey", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Project", "Project")
                        .WithMany("ApiKeys")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.DeviationEntry", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.ModelAlias", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.ModelCombo", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.OAuthAccount", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Tenant", "Tenant")
                        .WithMany("OAuthAccounts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Project", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Tenant", "Tenant")
                        .WithMany("Projects")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.ProviderAccount", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.ProviderModel", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.GlobalModel", "GlobalModel")
                        .WithMany("ProviderModels")
                        .HasForeignKey("GlobalModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalModel");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.RequestLog", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Project");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.RoutingPolicy", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.TenantModelLimit", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.GlobalModel", "GlobalModel")
                        .WithMany()
                        .HasForeignKey("GlobalModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalModel");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.TokenUsage", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Project");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.User", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Group", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", "Organization")
                        .WithMany("Groups")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Invitation", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", "Inviter")
                        .WithMany()
                        .HasForeignKey("InvitedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Group", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inviter");

                    b.Navigation("Organization");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.OrganizationSettings", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", "Organization")
                        .WithOne("Settings")
                        .HasForeignKey("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.OrganizationSettings", "OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Role", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", "Organization")
                        .WithMany("Roles")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.UserGroupMembership", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Group", "Group")
                        .WithMany("UserMemberships")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.UserOrganizationMembership", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", "Organization")
                        .WithMany("UserMemberships")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Group", "PrimaryGroup")
                        .WithMany()
                        .HasForeignKey("PrimaryGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", "User")
                        .WithMany("OrganizationMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("PrimaryGroup");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.UserRole", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.ProviderHealthStatus", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Operations.OrganizationProvider", "OrganizationProvider")
                        .WithMany()
                        .HasForeignKey("OrganizationProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrganizationProvider");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Platform.Model", b =>
                {
                    b.HasOne("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Platform.Provider", "Provider")
                        .WithMany("Models")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.GlobalModel", b =>
                {
                    b.Navigation("ProviderModels");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Project", b =>
                {
                    b.Navigation("ApiKeys");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Application.ControlPlane.Entities.Tenant", b =>
                {
                    b.Navigation("OAuthAccounts");

                    b.Navigation("Projects");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Group", b =>
                {
                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.Organization", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Roles");

                    b.Navigation("Settings");

                    b.Navigation("UserMemberships");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Identity.SynaxisUser", b =>
                {
                    b.Navigation("GroupMemberships");

                    b.Navigation("OrganizationMemberships");
                });

            modelBuilder.Entity("Synaxis.InferenceGateway.Infrastructure.ControlPlane.Entities.Platform.Provider", b =>
                {
                    b.Navigation("Models");
                });
#pragma warning restore 612, 618
        }
    }
}
