// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Synaxis.Infrastructure.Data;

#nullable disable

namespace Synaxis.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SynaxisDbContext))]
    [Migration("20260208232422_AddPerformanceIndexes")]
    partial class AddPerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Synaxis.Core.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("action");

                    b.Property<string>("EventCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_category");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("event_type");

                    b.Property<string>("IntegrityHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("integrity_hash");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PreviousHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("previous_hash");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("EventCategory");

                    b.HasIndex("EventType");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "Timestamp");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("Synaxis.Core.Models.BackupConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("EnableEncryption")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_encryption");

                    b.Property<bool>("EnablePostgresBackup")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_postgres_backup");

                    b.Property<bool>("EnableQdrantBackup")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_qdrant_backup");

                    b.Property<bool>("EnableRedisBackup")
                        .HasColumnType("boolean")
                        .HasColumnName("enable_redis_backup");

                    b.Property<string>("EncryptionKeyId")
                        .HasColumnType("text")
                        .HasColumnName("encryption_key_id");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("frequency");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastBackupAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_backup_at");

                    b.Property<string>("LastBackupStatus")
                        .HasColumnType("text")
                        .HasColumnName("last_backup_status");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("RetentionDays")
                        .HasColumnType("integer")
                        .HasColumnName("retention_days");

                    b.Property<int>("ScheduleHour")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_hour");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("strategy");

                    b.PrimitiveCollection<string[]>("TargetRegions")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationId", "IsActive");

                    b.ToTable("organization_backup_config", (string)null);
                });

            modelBuilder.Entity("Synaxis.Core.Models.CreditTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountUsd")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("amount_usd");

                    b.Property<decimal>("BalanceAfterUsd")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("balance_after_usd");

                    b.Property<decimal>("BalanceBeforeUsd")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("balance_before_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("InitiatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("initiated_by");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TransactionType");

                    b.HasIndex("OrganizationId", "CreatedAt");

                    b.ToTable("credit_transactions", (string)null);
                });

            modelBuilder.Entity("Synaxis.Core.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BillingCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("billing_currency");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<decimal>("ExchangeRate")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("exchange_rate");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmountBillingCurrency")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("total_amount_billing_currency");

                    b.Property<decimal>("TotalAmountUsd")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("total_amount_usd");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.HasIndex("Status");

                    b.HasIndex("OrganizationId", "PeriodStart", "PeriodEnd");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Synaxis.Core.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("AllowedEmailDomains")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("AvailableRegions")
                        .HasColumnType("text[]");

                    b.Property<string>("BillingCurrency")
                        .HasColumnType("text")
                        .HasColumnName("billing_currency");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("CreditBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("credit_balance");

                    b.Property<string>("CreditCurrency")
                        .HasColumnType("text");

                    b.Property<int>("DataRetentionDays")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsTrial")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean")
                        .HasColumnName("is_verified");

                    b.Property<int?>("MaxConcurrentRequests")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxKeysPerUser")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxTeams")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxUsersPerTeam")
                        .HasColumnType("integer");

                    b.Property<long?>("MonthlyRequestLimit")
                        .HasColumnType("bigint");

                    b.Property<long?>("MonthlyTokenLimit")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("PrimaryRegion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("primary_region");

                    b.Property<string>("PrivacyConsent")
                        .HasColumnType("jsonb")
                        .HasColumnName("privacy_consent");

                    b.Property<bool>("RequireSso")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime?>("SubscriptionExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("SubscriptionStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SubscriptionStatus")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TermsAcceptedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Tier")
                        .HasColumnType("text")
                        .HasColumnName("tier");

                    b.Property<DateTime?>("TrialEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TrialStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryRegion");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Tier");

                    b.ToTable("organizations", (string)null);
                });

            modelBuilder.Entity("Synaxis.Core.Models.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientIpAddress")
                        .HasColumnType("text")
                        .HasColumnName("client_ip_address");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("cost");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("CrossBorderTransfer")
                        .HasColumnType("boolean")
                        .HasColumnName("cross_border_transfer");

                    b.Property<int>("DurationMs")
                        .HasColumnType("integer")
                        .HasColumnName("duration_ms");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("input_tokens");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer")
                        .HasColumnName("output_tokens");

                    b.Property<string>("ProcessedRegion")
                        .HasColumnType("text")
                        .HasColumnName("processed_region");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<int>("QueueTimeMs")
                        .HasColumnType("integer")
                        .HasColumnName("queue_time_ms");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("jsonb")
                        .HasColumnName("request_headers");

                    b.Property<Guid>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<int>("RequestSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("request_size_bytes");

                    b.Property<int>("ResponseSizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("response_size_bytes");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.Property<string>("StoredRegion")
                        .HasColumnType("text")
                        .HasColumnName("stored_region");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("TransferLegalBasis")
                        .HasColumnType("text")
                        .HasColumnName("transfer_legal_basis");

                    b.Property<string>("TransferPurpose")
                        .HasColumnType("text")
                        .HasColumnName("transfer_purpose");

                    b.Property<DateTime?>("TransferTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transfer_timestamp");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("UserRegion")
                        .HasColumnType("text")
                        .HasColumnName("user_region");

                    b.Property<Guid?>("VirtualKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("virtual_key_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("CrossBorderTransfer");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("RequestId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.HasIndex("VirtualKeyId");

                    b.HasIndex("OrganizationId", "CreatedAt");

                    b.ToTable("requests", (string)null);
                });

            modelBuilder.Entity("Synaxis.Core.Models.SpendLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountUsd")
                        .HasColumnType("decimal(18,8)")
                        .HasColumnName("amount_usd");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("provider");

                    b.Property<string>("Region")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("region");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("request_id");

                    b.Property<Guid?>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int>("Tokens")
                        .HasColumnType("integer")
                        .HasColumnName("tokens");

                    b.Property<Guid?>("VirtualKeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("virtual_key_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("TeamId");

                    b.HasIndex("VirtualKeyId");

                    b.HasIndex("OrganizationId", "CreatedAt");

                    b.ToTable("spend_logs", (string)null);
                });

            modelBuilder.Entity("Synaxis.Core.Models.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Features")
                        .HasColumnType("jsonb")
                        .HasColumnName("features");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LimitsConfig")
                        .HasColumnType("jsonb")
                        .HasColumnName("limits_config");

                    b.Property<decimal?>("MonthlyPriceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("monthly_price_usd");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal?>("YearlyPriceUsd")
                        .HasColumnType("numeric")
                        .HasColumnName("yearly_price_usd");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("subscription_plans", (string)null);
                });

            modelBuilder.Entity("Synaxis.Core.Models.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("AllowedModels")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("BlockedModels")
                        .HasColumnType("text[]");

                    b.Property<decimal>("BudgetAlertThreshold")
                        .HasColumnType("numeric")
                        .HasColumnName("budget_alert_threshold");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<decimal?>("MonthlyBudget")
                        .HasColumnType("numeric")
                        .HasColumnName("monthly_budget");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Name");

                    b.HasIndex("OrganizationId", "Slug")
                        .IsUnique();

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("Synaxis.Core.Models.TeamMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("InvitedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("invited_by");

                    b.Property<Guid?>("InviterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("InviterId");

                    b.HasIndex("OrganizationId", "UserId");

                    b.HasIndex("TeamId", "UserId");

                    b.HasIndex("UserId", "TeamId")
                        .IsUnique();

                    b.ToTable("team_memberships", (string)null);
                });

            modelBuilder.Entity("Synaxis.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedInRegion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_in_region");

                    b.Property<DateTime?>("CrossBorderConsentDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cross_border_consent_date");

                    b.Property<bool>("CrossBorderConsentGiven")
                        .HasColumnType("boolean")
                        .HasColumnName("cross_border_consent_given");

                    b.Property<string>("CrossBorderConsentVersion")
                        .HasColumnType("text")
                        .HasColumnName("cross_border_consent_version");

                    b.Property<string>("DataResidencyRegion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("data_residency_region");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Locale")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("locale");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until");

                    b.Property<bool>("MfaEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("mfa_enabled");

                    b.Property<string>("MfaSecret")
                        .HasColumnType("text")
                        .HasColumnName("mfa_secret");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PrivacyConsent")
                        .HasColumnType("jsonb")
                        .HasColumnName("privacy_consent");

                    b.Property<string>("Role")
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Timezone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("timezone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("DataResidencyRegion");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("OrganizationId");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Synaxis.Core.Models.VirtualKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("AllowedModels")
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<string[]>("BlockedModels")
                        .HasColumnType("text[]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<decimal>("CurrentSpend")
                        .HasColumnType("numeric")
                        .HasColumnName("current_spend");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("key_hash");

                    b.Property<decimal?>("MaxBudget")
                        .HasColumnType("numeric")
                        .HasColumnName("max_budget");

                    b.Property<string>("Metadata")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid")
                        .HasColumnName("organization_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<string>("RevokedReason")
                        .HasColumnType("text")
                        .HasColumnName("revoked_reason");

                    b.Property<int?>("RpmLimit")
                        .HasColumnType("integer")
                        .HasColumnName("rpm_limit");

                    b.PrimitiveCollection<string[]>("Tags")
                        .HasColumnType("text[]");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<int?>("TpmLimit")
                        .HasColumnType("integer")
                        .HasColumnName("tpm_limit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserRegion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_region");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.HasIndex("OrganizationId", "Name");

                    b.HasIndex("OrganizationId", "TeamId");

                    b.ToTable("virtual_keys", (string)null);
                });

            modelBuilder.Entity("Synaxis.Core.Models.AuditLog", b =>
                {
                    b.HasOne("Synaxis.Core.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Synaxis.Core.Models.BackupConfig", b =>
                {
                    b.HasOne("Synaxis.Core.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Synaxis.Core.Models.CreditTransaction", b =>
                {
                    b.HasOne("Synaxis.Core.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Synaxis.Core.Models.Invoice", b =>
                {
                    b.HasOne("Synaxis.Core.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Synaxis.Core.Models.Request", b =>
                {
                    b.HasOne("Synaxis.Core.Models.Organization", "Organization")
                        .WithMany("Requests")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.Core.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Synaxis.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Synaxis.Core.Models.VirtualKey", "VirtualKey")
                        .WithMany("Requests")
                        .HasForeignKey("VirtualKeyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");

                    b.Navigation("Team");

                    b.Navigation("User");

                    b.Navigation("VirtualKey");
                });

            modelBuilder.Entity("Synaxis.Core.Models.SpendLog", b =>
                {
                    b.HasOne("Synaxis.Core.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.Core.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId");

                    b.HasOne("Synaxis.Core.Models.VirtualKey", "VirtualKey")
                        .WithMany()
                        .HasForeignKey("VirtualKeyId");

                    b.Navigation("Organization");

                    b.Navigation("Team");

                    b.Navigation("VirtualKey");
                });

            modelBuilder.Entity("Synaxis.Core.Models.Team", b =>
                {
                    b.HasOne("Synaxis.Core.Models.Organization", "Organization")
                        .WithMany("Teams")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Synaxis.Core.Models.TeamMembership", b =>
                {
                    b.HasOne("Synaxis.Core.Models.User", "Inviter")
                        .WithMany()
                        .HasForeignKey("InviterId");

                    b.HasOne("Synaxis.Core.Models.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.Core.Models.Team", "Team")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.Core.Models.User", "User")
                        .WithMany("TeamMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Inviter");

                    b.Navigation("Organization");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Synaxis.Core.Models.User", b =>
                {
                    b.HasOne("Synaxis.Core.Models.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("Synaxis.Core.Models.VirtualKey", b =>
                {
                    b.HasOne("Synaxis.Core.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Synaxis.Core.Models.Organization", "Organization")
                        .WithMany("VirtualKeys")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.Core.Models.Team", "Team")
                        .WithMany("VirtualKeys")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Synaxis.Core.Models.User", null)
                        .WithMany("VirtualKeys")
                        .HasForeignKey("UserId");

                    b.Navigation("Creator");

                    b.Navigation("Organization");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Synaxis.Core.Models.Organization", b =>
                {
                    b.Navigation("Requests");

                    b.Navigation("Teams");

                    b.Navigation("Users");

                    b.Navigation("VirtualKeys");
                });

            modelBuilder.Entity("Synaxis.Core.Models.Team", b =>
                {
                    b.Navigation("TeamMemberships");

                    b.Navigation("VirtualKeys");
                });

            modelBuilder.Entity("Synaxis.Core.Models.User", b =>
                {
                    b.Navigation("TeamMemberships");

                    b.Navigation("VirtualKeys");
                });

            modelBuilder.Entity("Synaxis.Core.Models.VirtualKey", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
