// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Synaxis.Infrastructure.Data;

#nullable disable

namespace Synaxis.Infrastructure.Data.Migrations
{
    [DbContext(typeof(SynaxisDbContext))]
    [Migration("20260209030000_AddInvitationEntity")]
    partial class AddInvitationEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");
#pragma warning restore 612, 618
        }
    }
}
